Repository SSUDevelog/EasyVel-iOS, pull requests merged in 2023-11, with the labels that each got.

#27 [FIX] #24 - 토스트 메시지 컬러 및 폰트 변경
  EasyVel/Presentation/Common/View/Toast.swift
  EasyVel/Presentation/Scrap/ScrapFolderBottomSheet/ScrapFolderBottomSheetViewController.swift
  EasyVel/Presentation/Scrap/ScrapStorage/ScrapStorageViewController.swift
  EasyVel/Presentation/Scrap/Storage/StorageViewController.swift
  EasyVel/Presentation/Search/FollowSearch/FollowSearchViewController.swift
  EasyVel/Presentation/Search/PostSearch/PostSearchViewController.swift
  EasyVel/Presentation/Search/TagSearch/TagSearchViewController.swift
  EasyVel/Presentation/Setting/ViewController/SettingViewController.swift
  EasyVel/Presentation/Sign/SignInViewController.swift
  EasyVel/Presentation/WebView/WebViewController.swift
  EasyVel/Util/Constant/TextLiterals.swift
Labels: fix

#30 [FEAT] #25 - 폴터추가 알럿 구현
  EasyVel.xcodeproj/project.pbxproj
  EasyVel/Presentation/Scrap/FolderAlert/View/FolderTextField.swift
  EasyVel/Presentation/Scrap/FolderAlert/ViewController/FolderAlertViewController.swift
  EasyVel/Presentation/Scrap/FolderAlert/ViewModel/FolderAlertViewModel.swift
  EasyVel/Presentation/Scrap/ScrapStorage/ScrapStorageViewController.swift
  EasyVel/Presentation/Scrap/ScrapStorage/ScrapStorageViewModel.swift
  EasyVel/Presentation/Scrap/ScrapStorage/View/ScrapStorageView.swift
  EasyVel/Presentation/Scrap/Storage/StorageViewController.swift
  EasyVel/Presentation/Scrap/Storage/StorageViewModel.swift
  EasyVel/Resource/Assets.xcassets/cancel.imageset/Contents.json
  EasyVel/Resource/Assets.xcassets/cancel.imageset/cancel.pdf
  EasyVel/Util/Constant/TextLiterals.swift
Labels: feat

#28 [FEAT] #17 - 스크랩한 글 확인할 수 있는 뷰의 리팩토링 & UI수정 완료했습니다
  EasyVel.xcodeproj/project.pbxproj
  EasyVel/Configuration/Info.plist
  EasyVel/Data/Model/StoragePost.swift
  EasyVel/Presentation/Common/View/Toast.swift
  EasyVel/Presentation/Scrap/ScrapStorage/ScrapStorageViewController.swift
  EasyVel/Presentation/Scrap/ScrapStorage/ScrapStorageViewModel.swift
  EasyVel/Presentation/Scrap/Storage/StorageViewController.swift
  EasyVel/Presentation/Scrap/Storage/StorageViewModel.swift
  EasyVel/Presentation/Scrap/Storage/View/DeleteFolderBottomSheet.swift
  EasyVel/Presentation/Scrap/Storage/View/StorageCollectionViewCell.swift
  EasyVel/Presentation/Scrap/Storage/View/StorageCollectionViewHeader.swift
  EasyVel/Presentation/Scrap/Storage/View/StorageHeadView.swift
  EasyVel/Presentation/Scrap/Storage/View/StoragePostView.swift
  EasyVel/Presentation/Scrap/Storage/View/StorageTableView.swift
  EasyVel/Presentation/Scrap/Storage/View/StorageTableViewCell.swift
  EasyVel/Presentation/Scrap/Storage/View/StorageView.swift
  EasyVel/Presentation/Scrap/Storage/ViewController/StorageViewController.swift
  EasyVel/Presentation/Scrap/Storage/ViewModel/StorageViewModel.swift
  EasyVel/Resource/Assets.xcassets/Exception/empty_scrap.imageset/Contents.json
  EasyVel/Resource/Assets.xcassets/Exception/empty_scrap.imageset/emptyScrap.pdf
  EasyVel/Resource/Assets.xcassets/closeCircle.imageset/Contents.json
  EasyVel/Resource/Assets.xcassets/closeCircle.imageset/closeCircle.pdf
  EasyVel/Resource/Assets.xcassets/closeIcon.imageset/Contents.json
  EasyVel/Resource/Assets.xcassets/closeIcon.imageset/closeIcon.pdf
  EasyVel/Util/Constant/ImageLiterals.swift
  EasyVel/Util/Constant/TextLiterals.swift
  EasyVel/Util/Extension/UITextField+Extension.swift
Labels: Chore, feat

#31 [REFACTOR] #29 - 웹뷰를 PostWeb 과 UserWeb 으로 나누었습니다
  EasyVel.xcodeproj/project.pbxproj
  EasyVel/Presentation/Follow/FollowViewController.swift
  EasyVel/Presentation/Follow/FollowViewModel.swift
  EasyVel/Presentation/Posts/PostsViewController.swift
  EasyVel/Presentation/Posts/PostsViewModel.swift
  EasyVel/Presentation/Scrap/ScrapPopUp/ScrapPopUpView.swift
  EasyVel/Presentation/Scrap/Storage/ViewController/StorageViewController.swift
  EasyVel/Presentation/Search/FollowSearch/FollowSearchViewController.swift
  EasyVel/Presentation/Search/FollowSearch/FollowSearchViewModel.swift
  EasyVel/Presentation/TabBar/TabBarController.swift
  EasyVel/Presentation/WebView/PostWebViewController.swift
  EasyVel/Presentation/WebView/PostWebViewModel.swift
  EasyVel/Presentation/WebView/UserWebViewController.swift
  EasyVel/Presentation/WebView/UserWebViewModel.swift
  EasyVel/Presentation/WebView/View/PostWebView.swift
  EasyVel/Presentation/WebView/WebViewController.swift
  EasyVel/Util/Extension/UIViewController+.swift
Labels: fix, feat
